### ISSUE TITLE
AST design guide lines

### ISSUE THREAD

**Issue by mar9000** [coolya/heavy-meta#1]
In extending my implementation of ECMAScript I had to take decisions on how to structuring language concepts hierarchy. In parsed languages like javascript one can try to adhere to:

1. parse tree
1. AST proposed by the library used for import.
1. none of the above and just follow minimum effort in MPS.

For instance the export statements:
```javascript
export {a, b};
export {a, b} from 'file.js';
```
are implemented with different node in the AST of shift-java (`ExportLocals` and `ExportFrom` respectively) but at parser, and probably at MPS level, would be better to implement with the same production/concept with an optional `FromClause`.

**Comment by coolya** [comment]
@mar9000 sorry for the delay. I would like to answer this one this thursday in the stream if that would fit for you. Otherwise I can also do it next week. I'm going to return to the usual Tuesday / Thursday schedule now.

**Comment by mar9000** [comment]
Hi, I saw the schedule. On thursday I have always an appointment around 20.30/21 so I can follow the first part of the streaming but not the whole one. On Tuesday I'm free the whole evening.

**Comment by coolya** [comment]
The lets schedule it for next Tuesday. :)
